#Geotagging for improved prediction of mortality due to border crossings at the U.S/Mexico border and the Mediterranean border. 

by Jasmin Martinez 
April 5, 2020 

#Introduction 

The purpose of this research is to improve upon the use of geotagging and geospatial intelligence data at international borders to generate a more specific number for monitoring the increase in mortality at international borders due to migration and identify problems by specifying, estimating, and validating a linear regression model as compared to previous models. Central to achieving this research goal of classifying migrants’ death due to the increase in border security through a linear regression model will be increasing the resolution of the United States/Mexico border and the Mediterranean Sea and through an accurate assessment of deaths. I will achieve this goal by meeting the following objectives: 

Use remotely sensed data to estimate the number of migrants crossing the U.S./Mexico border and the Mediterranean Sea border
 
Use survey data to estimate a linear regression model for predicting migrant death rates at the border, the rate of change of surveillance, and the rate of change of common routes taken by migrants
 
This work will build on previous research by Samuel Norton Chambers and Franziska Hübl and will incorporate new methods to implement an accurate count of mortality at the borders as well recent advances towards inferring how future an increase in surveillance and security as the border will have an impact on migrant mortality.  


Human Development Topic

Migration has been seen throughout centuries around the world. It has led to diversity and has allowed cultures to interact with one another. Migrants face a hard decision when deciding to leave their home countries due to economic, social, and political constraints and inequalities. To expand their real freedoms, migrants migrate to destination countries that provide a greater opportunity to increase these freedoms and progress in human development. I focused on two areas where migrant crossing has increased since the early 2000s: migration from Mexico to the United States, across the U.S./Mexico border, and migration from the Middle East to Greece, across the Mediterranean Sea. 

My dimension of human development relates to Amartya Sen’s definition of human development. Sen defines human development in his book Development as Freedom as “a process of expanding real freedoms that people enjoy.” My dimension relates to this definition when applied to the reasons for migrants leaving their home countries. Migrants face a hard decision to either stay in their home country to migrate to a destination country. For these migrants, the push factors include economic opportunities or jobs available to them, lack of social equality, lack of gender equality, and political oppression or constraints. With these push factors, there are also pull factors. Pull factors, towards moving to the destination country, include better living conditions and an increase in job opportunities. These are all examples of the freedoms migrants leave their home countries for and this expansion of real freedoms demonstrates how human migration is, arguably, an example of human development. 

This topic and research question arose from considering why these migrants are immigrating and the sustainable development goals that are being met or neglected and who they benefit. Migrants tend to leave their home countries to end poverty, which is the first sustainable development goal. People leave their home countries in order to look for economic opportunities abroad, where the minimum wage is usually higher, where there are more jobs available for unskilled workers, and more affordable housing with better living conditions. Migrants leave their homes to receive a quality education or ensure their children have the opportunity to do so, which is the fourth sustainable development goal. Finally, migrants may choose to leave their country of origin to reduce the overall inequalities that are present in their nations, which is the tenth sustainable development goal. While migrants are trying to meet these sustainable development goals by moving to their destination country they are unfortunately faced with an increase in innovation and infrastructure at these boards, which forces them to find alternative ways to enter these destination countries. This increase in innovation and infrastructure is part of the ninth sustainable development goal. This strive towards reaching these four sustainable development goals shows how an increase in sustainable development and human development process positive and negative facet to both migrants. Here, one can see the different perspectives on the impact of border security and in seeing this one can understand the difficult decisions destination countries must face when attempting to secure their borders.  

Human Development Process

The U.S./Mexico and Medditarrean Sea have seen an increase in migration from the early 2000s until now. These two borders have seen an increase in security and surveillance over the years due to the influx of migrants from the south. This increase has led to a “funnel effect” and pushed migrants to travel on routes that are more dangerous and high risk. I focused on the topic of human migration patterns to investigate if a correlation between increased security and increased mortality exists. 

At both borders, there are migrants crossing which are usually low-income and have seen a decline in education, economic, and social opportunities in their home countries [1]. Although these are all prominent push factors for these migrants, in “Who's crossing the border: new data on undocumented immigrants to the United States” Weeks explains that the biggest push factor is an increase in violence and corruption seen in these migrants countries of origin [1]. The weeks or months each migrant travels is full of dangerous terrain with unpredictable circumstances. As the number of migrants crossing these borders have increased, so have the efforts of nations to stop migrants from entering into their countries. An increase in surveillance and security at these borders has decreased the rate of migrants attempting to cross into their destination countries [2]. But, the migrants that are still attempting to cross this increase have led them to cross at areas that are more isolated and dangerous to go unnoticed and decrease apprehension risks [2]. This pattern, seen at the Medditarean border and the U.S./Mexico border is known as the “funnel effect”, defined as the forcing of migrants to travel through areas of high risk [3]. This has created hotspots in areas with less security and cold spots in areas that are known for high rates of apprehension [3]. At the Mediterranean border, there were 4,690 deaths reported in 2016, which was the year with the highest rate of migrants crossing [6].  

The increase in mortality at both borders shows how this process behaves as a complex adaptive system. As nations begin to criminalize unauthorized migration, there seems to be an increase in funding for security at these borders- both in manpower and physical barriers [2]. This increase in security leaves migrants forced to find new routes to enter their destination countries and in attempting to adapt to this change they are faced with new, unknown, and dangerous terrain. This new risk has led to an increase in migrant mortality. In “Mortality, Surveillance and the Tertiary “Funnel Effect” on the U.S.-Mexico Border: A Geospatial Modeling of the Geography of Deterrence” Chambers introduces the appalling fact that increased surveillance at the U.S./Mexico border has led to a 20-fold increase in death and disappearance of migrants [3]. Since the early 2000s, both borders have been through a process of emergence and, with rates of incoming migrants increasing, the emergence does not seem to decrease at any time in the near future. 

Geospatial Data Science Methods

I looked at the data collected from the apprehensions made at the border. In “The Effects of Geospatial-Intelligence on United States-Mexico Border Security” report the U.S. interpretation of the securitization theory and increase in geospatial intelligence (GEOINT) is introduced to address the increase in security on the U.S.-Mexico border. The securitization theory emphasizes an extraordinary means to be used in the name of security, which has been seen at the southern border since the event of 9/11. In this report data from GEOINT, which provides situational awareness of crossings, and Customs Border Patrol (CBP) was used to create geospatial maps demonstrating the “operational control of the border” and displaying areas where the illegal crossing was occurring. The main focus of this report was the illegal entries correlated with drug crime and the research recognized that free migration should be provided to those escaping situations which prohibit their freedoms and hinder human development [2]. 

From the research, it was found that there was a correlation between increased manning and funding and a decreased apprehension rate at the border. This increase in manpower and the use of technology to secure the border has provided a perception that the border is a dangerous place and has added to the narrative of a “border crisis” present at the southern border. This has led many Americans to fear the entry of migrants from the south and many migrants to fear apprehension and detainment at the border. This fear instilled in migrants along with the increase in manning has not stopped migrants from crossing. These two factors have increased the number of attempts at the crossing before successful and have sparked an increase to cross in larger groups to increase the chance to escape if caught. These factors have also led to migrants deciding to cross at areas that are more isolated and dangerous to go unnoticed, which has, unfortunately, increased the number of fatalities at the U.S.-Mexico border [2]. 

This decision to cross at high-risk areas was introduced as the “funnel effect.”
This forces migrants to travel through areas of high risk which has resulted in an increase in mortality at the southern border. The study by Chambers analyzed data from 1994 to 2015 and looked at an area of 259,981 hectares along the Arizona/Sonora border between the cities of Arivaca, Arizona and Sasabe, Sonora. The research used data from SBInet and Customs and Border Patrol (CBP) to measure the surveillance present in this area and the total caloric cost (TCC) to cross into the U.S. Then, the total mortality on these routes was analyzed and a correlation was established [3]. 

The research found that the increase in surveillance between the region led to a 20-fold increase in death and the disappearance of migrants. Within the area of investigation, 49 mortalities were found and documented. Around these morality sites, the least-cost paths (LCP) and diverted least-cost paths (DLCP) were found which allowed for the calculation of TCC on these routes. On the LCP, the mean TCC was 3281.47 while on the DLCP the mean TCC was 4207.45. In recent years, the increased surveillance has forced migrants to travel on these DLCPs which in turn has led to deaths caused by “exposure to the elements- dehydration, hyperthermia, and physical exertion.”  Physical exertion accounted for 45% of all recorded migrant deaths, and with the TCC seen on the DLCPs along with the environmental risks present, it makes sense [3]. 

The situation at the Mediterranean border was analyzed in a completely different way, through geo-tagging. In the report “Analyzing Refugee Migration Patterns Using Geo-Tagged Tweets”, Hubl uses geo-tagging to identify the refugee migration patterns from the Middle East to Europe. The data is collected from Twitter and is composed of the user name, creation time and date, position coordinates, and hashtags. The hashtags were the main source to find refugees and once tweets posted by these refugees were found, the position coordinates could be used to track the pattern of migration. For a tweet to be considered part of the data set there must be a tweet posted in at least one location outside of Europe followed by a location in Europe. Although a limitation is observed since not all refugees are twitter or access to it, there may be a variation in migration patterns between those who use twitter and those who don’t but the study still allows to display generalized patterns of migration by these refugees [4]. 

Hubl concludes that the primary refugee route was along the Mediterranean Sea into port cities in Greece. Distance-bounded eventing clustering was used to conclude this with the help of geo-tags from tweets of refugees[8]. This also increases the thought of the danger associated with this form of travel and how increased security at sea can harm asylum-seekers and refugees making this journey. The drive to understand these migration patterns is mainly for administrative logistics, which include accommodation, transportation, education, and distribution of refugees. All efforts to help refugees develop in these European countries that are unknown to them. By increasing the quality of life for these refugees in these new nations there is an expansion of freedoms related that also help to increase global human development. With this, refugees can expand their social, economic, and political freedoms. But one must also consider the excessive amounts of risks that come with this form of travel, such as getting lost and becoming victims of trafficking and robbery. This report gives a good insight into the migration patterns and routes taken by these refugees and also takes into consideration the tenth UN sustainable development goal, reduced inequality[4].
 
Discussion


Throughout my research, it posed difficult to find geospatial data to describe the phenomenons that were occurring at these borders. The main issue was presented in finding an accurate number of migrants that had disappeared or died at each border. I started by researching how migration routes have changed between both borders and then continued by researching the rate of mortality at each border. So far, I have been able to see the routes that migrants have taken in the past and the routes that are being taken more commonly today. These new routes have definitely been impacted by the increase in security that has been seen, but I have yet to find a report that can accurately estimate how much of an impact the increase in security has really made. My objective is to investigate how morality can be accurately accounted for at these border crossings and then investigate the correlation these deaths have with the increase in security. 


References 

[1]  Weeks, J. R., Stoler, J., & Jankowski, P. (2010, December 27). Who's crossing the border: new data on undocumented immigrants to the United States. Retrieved February 16, 2020, from https://www.doi.org/10.1002/psp.563

[2] Martin, H. (2018). The Effects of Geospatial-Intelligence on United States-Mexico Border Security. Retrieved February 16, 2020, from https://www.aquila.usm.edu/cgi/viewcontent.cgi?article=2556&context=dissertations 

[3] Samuel Norton Chambers, Geoffrey Alan Boyce, Sarah Launius & Alicia Dinsmore (January 31, 2019). Mortality, Surveillance and the Tertiary “Funnel Effect” on the U.S.-Mexico border: A Geospatial Modeling of the Geography of Deterrence. Journal of Borderlands Studies. Retrieved on February 16, 2020, from https://www.doi.org/10.1080/08865655.2019.1570861

[4] Hübl, Franziska. Cvetojevic, Sreten. Hochmair, Hartwig. & Paulus, Gernot (2017, October 2). Analyzing Refugee Migration Patterns Using Geo-Tagged Tweets. Retrieved February 16, 2020, from www.mdpi.com/2220-9964/6/10/302.

[5] Datta, Anusya. (2016, December 12). These Maps Tell You All About Global Refugee Movement and Fatalities. Geospatial World. Retrieved February 17, 2020, from https://www.geospatialworld.net/blogs/global-refugee-movement-and-fatalities/. 

[6] Carrera, Sergio. Et al. (2016). The European Border and Coast Guard: Addressing migration and asylum challenges in the Mediterranean. Retrieved March 30, 2020, from http://www.aei.pitt.edu/83997/1/TFR_EU_Border_and_Coast_Guard_with_cover_0.pdf

[7] Greenough, Gregg & Nelson, Erica (2019, November 08). Beyond mapping: a case for geospatial analytics in humanitarian health. Retrieved March 30, 2020, from https://www.conflictandhealth.biomedcentral.com/articles/10.1186/s13031-019-0234-9 

[8] Hubl, Franziska (2016 August). Analysis of Migration Patterns of Refugees using Geotagged Tweets. Retrieved March 30, 2020, from https://www.static1.squarespace.com/static/559921a3e4b02c1d7480f8f4/t/596ca3bf2e69cffeddbee291/1500292041794/Huebl+Franziska_625.pdf 

[9] Brian, Tara & Laczko, Frank. Fatal Journeys: Tracking Lives Lost during Migration. Retrieved March 30, 2020, from http://www.lastradainternational.org/lsidocs/3089-FatalJourneys.pdf#page=87

[10] Wolff, Sarah (2008 June 2). Border management in the Mediterranean: internal, external and ethical challenges. Retrieved March 30, 2020, from https://www.researchgate.net/profile/Sarah_Wolff4/publication/249017147_Border_Management_in_the_Mediterranean_Internal_External_and_Ethical_Challenges/links/545356430cf26d5090a3af40.pdf 


